const prompts = [
  "Write a persuasive essay about climate change",
  "Compose a love letter in Victorian style",
  "Write a science fiction story about AI",
  "Create a formal business proposal",
  "Write a philosophical dialogue about consciousness",
  "Compose a heartfelt thank you letter",
  "Write a movie review in a critical style",
  "Create a detailed character description",
  "Write a travel blog post about a fictional city",
  "Compose a formal complaint letter",
  "Write a fantasy story opening chapter",
  "Create a professional job application letter",
  "Write a newspaper article about future technology",
  "Compose a poem about nature",
  "Write a personal memoir excerpt",
  "Create a marketing copy for a product",
  "Write a historical fiction scene",
  "Compose a letter of recommendation",
  "Write a mystery story introduction",
  "Create a restaurant review",
  "Write a motivational speech script",
  "Compose a wedding toast",
  "Write a children's bedtime story",
  "Create a professional networking message",
  "Write a horror story scene",
  "Compose a letter of apology",
  "Write a product description",
  "Create a biography excerpt",
  "Write a romantic comedy scene",
  "Compose a graduation speech",
  "Write a technical tutorial introduction",
  "Create a cover letter template",
  "Write a detective story opening",
  "Compose a farewell letter",
  "Write a blog post about personal growth",
  "Create a movie script scene",
  "Write a book review",
  "Compose a letter of resignation",
  "Write a fantasy world description",
  "Create a social media post",
  "Write a political speech",
  "Compose a love poem",
  "Write a scientific article abstract",
  "Create a professional email",
  "Write a thriller story scene",
  "Compose a eulogy",
  "Write a product review",
  "Create a mission statement",
  "Write a comedy sketch script",
  "Compose a letter of invitation",
  "Write a self-help article",
  "Create a press release",
  "Write a dystopian story scene",
  "Compose a letter of condolence",
  "Write a travel guide excerpt",
  "Create a company newsletter",
  "Write a dramatic monologue",
  "Compose a letter of introduction",
  "Write a food review",
  "Create a research paper abstract",
  "Write a coming-of-age story scene",
  "Compose a congratulatory message",
  "Write an opinion editorial",
  "Create a user manual introduction",
  "Write a mystery novel synopsis",
  "Compose a business memo",
  "Write a biographical sketch",
  "Create a podcast script",
  "Write a fantasy quest description",
  "Compose a letter of support",
  "Write a technical report summary",
  "Create a blog post outline",
  "Write a romantic scene",
  "Compose a letter of feedback",
  "Write a news report",
  "Create a presentation script",
  "Write a character dialogue",
  "Compose a letter of inquiry",
  "Write a product launch announcement",
  "Create a documentary script",
  "Write a personal essay",
  "Compose a letter of appeal",
  "Write a short story ending",
  "Create a workshop description",
  "Write a debate speech",
  "Compose a letter of reference",
  "Write a magazine article",
  "Create a video script",
  "Write a memoir chapter",
  "Compose a letter of acceptance",
  "Write a literary analysis",
  "Create a course description",
  "Write a comedy routine",
  "Compose a letter of complaint",
  "Write a feature article",
  "Create a training manual introduction",
  "Write a suspense story scene",
  "Compose a letter of appreciation",
  "Write an interview script",
  "Create a case study narrative"
];

export const getRandomPrompts = () => {
    const randomPrompts = [];
    for (let i = 0; i < 3; i++) {
        const randomIndex = Math.floor(Math.random() * prompts.length);
        randomPrompts.push(prompts[randomIndex]);
    }
    return randomPrompts;
}